### PR TITLE
Add pre-commit configuration

### LINKED ISSUE #77: Add a pre-commit config

### PR DESCRIPTION
**Pull request by dokempf**
This fixes #77

### CODE REVIEW

**Comment by lkeegan** [comment]
This works for me locally, no idea what the CI error is..

**Comment by dokempf** [comment]
I haved fixed the CI. Do you agree with the approach of generating `.pre-commit-config.yml` if and only if the user has pre-commit installed? I wanted to avoid config bloat and also not generate too much that the user did not ask for.

**Comment by lkeegan** [comment]
Yes I think that makes sense - maybe we could add a sentence to the readme to say that if you have pre-commit installed it will also generate a pre-commit config file?

**Review by lkeegan — APPROVED** [review]

**Comment by dokempf** [comment]
That sentence already is in the README as part of the feature list

**Pull request merged**
