### PR TITLE
Badges

### LINKED ISSUE #24: Whitespace control between badges
Currently, each badge is on a newline. This is much harder than you think, because stripping all whitespace from all badges will result in all badges being glued to the content above and below, need to dive the Jinja docs for a solution

### PR DESCRIPTION
**Pull request by dokempf**
This fixes #24 & #15

### CODE REVIEW

**Comment by dokempf** [comment]
The badges can be seen in the deployed test repo here: https://github.com/dokempf/test-github-actions-cookiecutter-cpp-project

**Comment by dokempf** [comment]
The fact that there is two `build - passing` badges is that there are two CI providers. Users typically will not have this.

**Comment by dokempf** [comment]
The above statement of two badges vanishes with the removal of Travis

**Review by iulusoy — APPROVED** [review]

**Review by lkeegan — APPROVED** [review]
lgtm - I tried it out and all the badges are present & link to the right place as far as I can see:
- https://github.com/lkeegan/temp-test
- https://gitlab.com/lkeegan1/temp-test

**Pull request merged**
